$file = "c:\Users\hp\OneDrive\Desktop\Kasa_Saffron Home\kasa-saffron-react\src\App.css"
$lines = Get-Content $file -Encoding UTF8
$before = $lines[0..1347]
$after = $lines[1777..($lines.Count-1)]
$newLines = @(
"/* ═══════════════════════════════════════════════════════════════════",
"   NEOMORPHIC STORYTELLING — REVEAL ANIMATION",
"   ═══════════════════════════════════════════════════════════════════ */",
"",
".mob-reveal {",
"    opacity: 0;",
"    transform: translateY(32px);",
"    will-change: transform, opacity;",
"    transition: opacity 1s cubic-bezier(0.22, 1, 0.36, 1),",
"                transform 1s cubic-bezier(0.22, 1, 0.36, 1);",
"}",
"",
".mob-reveal.mob-revealed {",
"    opacity: 1;",
"    transform: translateY(0);",
"}",
"",
"/* Stagger children */",
".mob-features-list .mob-reveal:nth-child(2) { transition-delay: 0.12s; }",
".mob-features-list .mob-reveal:nth-child(3) { transition-delay: 0.24s; }",
".mob-features-list .mob-reveal:nth-child(4) { transition-delay: 0.36s; }",
"",
"",
"/* ═══════════════════════════════════════════════════════════════════",
"   SECTION 2: OUR STORY",
"   ═══════════════════════════════════════════════════════════════════ */",
"",
".mob-story-section {",
"    padding: 56px 20px 40px;",
"    background: linear-gradient(180deg, #f9efe7 0%, #ece0d4 100%);",
"    position: relative;",
"}",
"",
".mob-story-header {",
"    text-align: center;",
"    margin-bottom: 32px;",
"}",
"",
".mob-story-badge {",
"    display: inline-block;",
"    font-family: 'Montserrat', sans-serif;",
"    font-size: 9px;",
"    font-weight: 700;",
"    letter-spacing: 4px;",
"    color: #B08D57;",
"    text-transform: uppercase;",
"    margin-bottom: 10px;",
"}",
"",
".mob-story-title {",
"    font-family: 'Cormorant Garamond', serif;",
"    font-size: 28px;",
"    font-weight: 600;",
"    color: #3a0d16;",
"    line-height: 1.15;",
"    margin: 0;",
"    letter-spacing: 0.5px;",
"}",
"",
".mob-story-title-line {",
"    width: 40px;",
"    height: 1.5px;",
"    background: linear-gradient(90deg, transparent, #B08D57, transparent);",
"    margin: 14px auto 0;",
"}",
"",
"",
"/* ── Neomorphic Card ── */",
".mob-neu-card {",
"    background: linear-gradient(145deg, #f3e8dc, #e5dacd);",
"    border-radius: 24px;",
"    padding: 28px 22px 24px;",
"    box-shadow:",
"        9px 9px 18px rgba(175, 155, 135, 0.55),",
"        -9px -9px 18px rgba(255, 255, 255, 0.9);",
"    border: 1px solid rgba(255, 255, 255, 0.45);",
"}",
"",
"",
"/* ── Founder Block ── */",
".mob-founder-block {",
"    margin-bottom: 24px;",
"}",
"",
".mob-founder-block:last-of-type {",
"    margin-bottom: 0;",
"}",
"",
".mob-founder-img-wrap {",
"    width: 100px;",
"    height: 100px;",
"    border-radius: 50%;",
"    margin: 0 auto 18px;",
"    padding: 3px;",
"    background: linear-gradient(135deg, #E6C587, #B08D57, #E6C587);",
"    box-shadow:",
"        4px 4px 12px rgba(180, 160, 140, 0.6),",
"        -4px -4px 12px rgba(255, 255, 255, 0.8);",
"}",
"",
".mob-founder-img {",
"    width: 100%;",
"    height: 100%;",
"    border-radius: 50%;",
"    object-fit: cover;",
"    border: 3px solid #ece0d4;",
"}",
"",
".mob-founder-info {",
"    text-align: center;",
"}",
"",
".mob-founder-name {",
"    font-family: 'Cormorant Garamond', serif;",
"    font-size: 24px;",
"    font-weight: 700;",
"    color: #3a0d16;",
"    margin: 0 0 4px;",
"    letter-spacing: 0.3px;",
"}",
"",
".mob-founder-role {",
"    display: block;",
"    font-family: 'Montserrat', sans-serif;",
"    font-size: 9px;",
"    font-weight: 700;",
"    letter-spacing: 3px;",
"    color: #B08D57;",
"    text-transform: uppercase;",
"}",
"",
".mob-founder-line {",
"    width: 36px;",
"    height: 1px;",
"    background: linear-gradient(90deg, transparent, rgba(176, 141, 87, 0.5), transparent);",
"    margin: 14px auto;",
"}",
"",
".mob-founder-quote {",
"    font-family: 'Cormorant Garamond', serif;",
"    font-size: 14px;",
"    font-style: italic;",
"    line-height: 1.7;",
"    color: #5a3a2a;",
"    margin: 0;",
"    max-width: 300px;",
"    margin-left: auto;",
"    margin-right: auto;",
"}",
"",
"",
"/* ═══════════════════════════════════════════════════════════════════",
"   SECTION 3: WHAT WE DO (OUR CRAFT)",
"   ═══════════════════════════════════════════════════════════════════ */",
"",
".mob-craft-section {",
"    background: linear-gradient(180deg, #ece0d4 0%, #f0e4da 100%);",
"}",
"",
".mob-features-list {",
"    display: flex;",
"    flex-direction: column;",
"    gap: 14px;",
"    margin-bottom: 28px;",
"}",
"",
".mob-feature-pill {",
"    display: flex;",
"    align-items: flex-start;",
"    gap: 16px;",
"    background: linear-gradient(145deg, #f3e8dc, #e5dacd);",
"    border-radius: 20px;",
"    padding: 20px 18px;",
"    box-shadow:",
"        6px 6px 14px rgba(175, 155, 135, 0.5),",
"        -6px -6px 14px rgba(255, 255, 255, 0.85);",
"    border: 1px solid rgba(255, 255, 255, 0.4);",
"}",
"",
".mob-feature-icon {",
"    width: 44px;",
"    height: 44px;",
"    flex-shrink: 0;",
"    display: flex;",
"    align-items: center;",
"    justify-content: center;",
"    background: #e5dacd;",
"    border-radius: 14px;",
"    box-shadow:",
"        inset 4px 4px 8px rgba(175, 155, 135, 0.45),",
"        inset -4px -4px 8px rgba(255, 255, 255, 0.7);",
"}",
"",
".mob-feature-text {",
"    flex: 1;",
"    min-width: 0;",
"}",
"",
".mob-feature-text h3 {",
"    font-family: 'Montserrat', sans-serif;",
"    font-size: 12px;",
"    font-weight: 700;",
"    color: #3a0d16;",
"    margin: 0 0 4px;",
"    letter-spacing: 0.3px;",
"}",
"",
".mob-feature-text p {",
"    font-size: 11px;",
"    line-height: 1.55;",
"    color: rgba(58, 13, 22, 0.65);",
"    margin: 0;",
"    font-weight: 400;",
"}",
"",
"",
"/* ── Neomorphic CTA Buttons ── */",
".mob-neu-cta-group {",
"    display: flex;",
"    flex-direction: column;",
"    gap: 12px;",
"}",
"",
".mob-neu-btn-primary {",
"    display: block;",
"    width: 100%;",
"    text-align: center;",
"    text-decoration: none;",
"    padding: 16px 0;",
"    border-radius: 60px;",
"    font-family: 'Montserrat', sans-serif;",
"    font-size: 11px;",
"    font-weight: 800;",
"    text-transform: uppercase;",
"    letter-spacing: 3px;",
"    color: #E6C587;",
"    background: linear-gradient(135deg, #3a0d16 0%, #2a0810 100%);",
"    box-shadow:",
"        6px 6px 16px rgba(180, 160, 140, 0.6),",
"        -4px -4px 12px rgba(255, 248, 240, 0.6),",
"        inset 0 1px 0 rgba(230, 197, 135, 0.15);",
"    transition: transform 0.25s ease, box-shadow 0.25s ease;",
"}",
"",
".mob-neu-btn-primary:active {",
"    transform: scale(0.97);",
"    box-shadow:",
"        inset 4px 4px 10px rgba(0, 0, 0, 0.4),",
"        inset -2px -2px 6px rgba(230, 197, 135, 0.1);",
"}",
"",
".mob-neu-btn-secondary {",
"    display: block;",
"    width: 100%;",
"    text-align: center;",
"    text-decoration: none;",
"    padding: 15px 0;",
"    border-radius: 60px;",
"    font-family: 'Montserrat', sans-serif;",
"    font-size: 11px;",
"    font-weight: 700;",
"    text-transform: uppercase;",
"    letter-spacing: 3px;",
"    color: #3a0d16;",
"    background: linear-gradient(145deg, #f3e8dc, #e5dacd);",
"    border: none;",
"    box-shadow:",
"        6px 6px 16px rgba(175, 155, 135, 0.5),",
"        -6px -6px 16px rgba(255, 255, 255, 0.8);",
"    transition: transform 0.25s ease, box-shadow 0.25s ease;",
"}",
"",
".mob-neu-btn-secondary:active {",
"    transform: scale(0.97);",
"    box-shadow:",
"        inset 4px 4px 10px rgba(175, 155, 135, 0.4),",
"        inset -3px -3px 8px rgba(255, 255, 255, 0.6);",
"}",
"",
"",
"/* ═══════════════════════════════════════════════════════════════════",
"   SECTION 4: MOBILE FOOTER (Neomorphic theme)",
"   ═══════════════════════════════════════════════════════════════════ */",
"",
".mob-story-footer {",
"    background: #1a0a0d;",
"    padding: 44px 24px 32px;",
"    width: 100%;",
"    border-top: 1px solid rgba(230, 197, 135, 0.12);",
"}",
"",
".mob-story-footer .mob-footer-inner {",
"    display: flex;",
"    flex-direction: column;",
"    align-items: center;",
"    text-align: center;",
"    gap: 16px;",
"    max-width: 100%;",
"    width: 100%;",
"}",
"",
".mob-story-footer .mob-footer-logo {",
"    width: 70px;",
"    filter: drop-shadow(0 2px 8px rgba(230, 197, 135, 0.2));",
"}",
"",
".mob-story-footer .mob-footer-tagline {",
"    font-size: 11px;",
"    line-height: 1.7;",
"    color: rgba(246, 229, 221, 0.65);",
"    font-weight: 300;",
"    max-width: 280px;",
"}",
"",
".mob-story-footer .mob-footer-divider {",
"    width: 60px;",
"    height: 1px;",
"    background: linear-gradient(90deg, transparent, rgba(230, 197, 135, 0.3), transparent);",
"    margin: 4px 0;",
"}",
"",
".mob-story-footer .mob-footer-links {",
"    display: flex;",
"    flex-wrap: wrap;",
"    justify-content: center;",
"    gap: 6px 16px;",
"}",
"",
".mob-story-footer .mob-footer-links a {",
"    font-size: 11px;",
"    color: rgba(246, 229, 221, 0.85);",
"    text-decoration: none;",
"    font-weight: 400;",
"    letter-spacing: 0.5px;",
"    transition: color 0.2s;",
"}",
"",
".mob-story-footer .mob-footer-links a:active {",
"    color: #E6C587;",
"}",
"",
".mob-story-footer .mob-footer-contact {",
"    display: flex;",
"    flex-direction: column;",
"    gap: 4px;",
"}",
"",
".mob-story-footer .mob-footer-contact p,",
".mob-story-footer .mob-footer-contact a {",
"    font-size: 10px;",
"    color: rgba(246, 229, 221, 0.55);",
"    text-decoration: none;",
"    font-weight: 300;",
"}",
"",
".mob-story-footer .mob-footer-contact-btn {",
"    display: inline-flex;",
"    align-items: center;",
"    gap: 6px;",
"    padding: 8px 20px;",
"    border: 1px solid rgba(230, 197, 135, 0.4);",
"    border-radius: 60px;",
"    background: transparent;",
"    color: #E6C587;",
"    font-family: 'Montserrat', sans-serif;",
"    font-size: 10px;",
"    font-weight: 700;",
"    letter-spacing: 2px;",
"    text-transform: uppercase;",
"    cursor: pointer;",
"    transition: background 0.2s, color 0.2s;",
"}",
"",
".mob-story-footer .mob-footer-contact-btn:active {",
"    background: #E6C587;",
"    color: #1a0104;",
"}",
"",
".mob-story-footer .mob-footer-social {",
"    display: flex;",
"    gap: 14px;",
"}",
"",
".mob-story-footer .mob-footer-social a {",
"    width: 36px;",
"    height: 36px;",
"    border-radius: 50%;",
"    border: 1px solid rgba(230, 197, 135, 0.2);",
"    display: flex;",
"    align-items: center;",
"    justify-content: center;",
"    color: rgba(230, 197, 135, 0.8);",
"    text-decoration: none;",
"    transition: border-color 0.2s, color 0.2s;",
"}",
"",
".mob-story-footer .mob-footer-social a:active {",
"    border-color: #E6C587;",
"    color: #E6C587;",
"}",
"",
".mob-story-footer .mob-footer-copy {",
"    margin-top: 4px;",
"}",
"",
".mob-story-footer .mob-footer-copy p {",
"    font-size: 9px;",
"    color: rgba(246, 229, 221, 0.35);",
"    font-weight: 300;",
"    margin: 0;",
"    line-height: 1.5;",
"}"
)
$result = $before + $newLines + $after
[IO.File]::WriteAllLines($file, $result, [System.Text.Encoding]::UTF8)
Write-Host "Replaced lines properly with UTF8 Encoding without BOM."
